services:
  postgres:
    image: postgres:18.1
    container_name: flygeracademyDB
    restart: always
    environment:
      POSTGRES_USER: nahim
      POSTGRES_PASSWORD: nahim
      POSTGRES_DB: flygeracademyDB
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
